name: flashcard-app
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - streamlit
  - sqlite
  - pandas
  - matplotlib
  - plotly
  - sqlalchemy
  - pip
  - pip:
      - streamlit-option-menu
