name: flashcard-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - streamlit
  - pandas
  - matplotlib-base
  - plotly
  - sqlalchemy
  - pip
  - pip:
    - streamlit-option-menu
